### ISSUE TITLE
Isotope sortBy Issue

### ISSUE THREAD

**Issue by andrewsquire23** [metafizzy/isotope#1230]
**Use case**

Originally the following code worked fine with Isotope v1. My goal is to sort isotope elements so that var $item which hasClass 'selected' is first element in the isotope #grid.

```
var $container = $('#grid'),
          $item = $('.cell');
        $container.isotope({
          itemSelector: '.cell',
          percentPosition: true,
          packery: {
            columnWidth: '.cell-sizr',
            gutter: 0
          },
          getSortData : {
          selected : function( $item ){
            // sort by selected first, then by original order
            return ($item.index('selected') ? -500 : 0) + $item.index();
          }
        },
        sortBy : 'selected'
        });
```

Notes

Originally like I had mentioned before, the code worked in Isotope v1. I used the following code to implement from: http://jsfiddle.net/ttf5776r/12/ But for whatever reason after migrating to v2 the code is broken with the following error:

```
Uncaught TypeError: $item.hasClass is not a function
    at selected (pf.js:85)
    at e.i.updateSortData (isotope.pkgd.min.js:11)
    at e.l._updateItemsSortData (isotope.pkgd.min.js:11)
    at e.l._itemize (isotope.pkgd.min.js:11)
    at e.c.reloadItems (isotope.pkgd.min.js:11)
    at e.l.reloadItems (isotope.pkgd.min.js:11)
    at e.c._create (isotope.pkgd.min.js:11)
    at e.l._create (isotope.pkgd.min.js:11)
    at e.s (isotope.pkgd.min.js:11)
    at new e (isotope.pkgd.min.js:11)

``````

**Comment by desandro** [comment]
In Isotope v2 and v3, the argument in the [getSortData function](http://isotope.metafizzy.co/sorting.html#getsortdata-functions) is no longer a jQuery object, but an element. To update your code, wrap the `item` in a jQuery object.

``` js
getSortData : {
  selected : function( item ){
    var $item = $(item);
    // sort by selected first, then by original order
    return ($item.index('selected') ? -500 : 0) + $item.index();
  }
}
```


See demo http://jsfiddle.net/ttf5776r/15/

**Comment by andrewsquire23** [comment]
Thank you @desandro! :)
